# Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# SPDX-License-Identifier: MIT

"""Executable contract tests for the reviewed Rust adapter family."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from copy import deepcopy
from pathlib import Path
from typing import Any
from unittest import mock

from awq import adapters
from scripts.validate_contracts import validate
from tests.support import Repository

STABLE_IDS = [
    "ADAPTER-RUST-BUILD",
    "ADAPTER-RUST-CLIPPY",
    "ADAPTER-RUST-DOC",
    "ADAPTER-RUST-FMT",
    "ADAPTER-RUST-TEST",
]
EXPECTED_IDS = [
    "ADAPTER-RUST-ADVISORY",
    "ADAPTER-RUST-BUILD",
    "ADAPTER-RUST-CLIPPY",
    "ADAPTER-RUST-DOC",
    "ADAPTER-RUST-FMT",
    "ADAPTER-RUST-POLICY",
    "ADAPTER-RUST-SEMVER",
    "ADAPTER-RUST-TEST",
]
CONFIG_PATHS = [
    ".cargo/config.toml",
    "Cargo.lock",
    "Cargo.toml",
    "rust-toolchain.toml",
]
TOOLCHAIN = (
    '[toolchain]\nchannel = "1.93.0"\nprofile = "minimal"\ncomponents = ["clippy", "rustfmt"]\n'
)
MANIFEST = (
    '[package]\nname = "awq-rust-fixture"\nversion = "0.1.0"\n'
    'edition = "2024"\npublish = false\n\n[lib]\npath = "src/lib.rs"\n'
    "doctest = true\n"
)
LOCK = (
    "# This file is automatically @generated by Cargo.\n"
    "# It is not intended for manual editing.\n"
    "version = 4\n\n"
    "[[package]]\n"
    'name = "awq-rust-fixture"\n'
    'version = "0.1.0"\n'
)
SOURCE = """//! Positive Rust adapter fixture.

/// Add two unsigned values.
///
/// # Examples
///
/// ```
/// assert_eq!(awq_rust_fixture::add(2, 3), 5);
/// ```
#[must_use]
pub const fn add(left: u64, right: u64) -> u64 {
    left + right
}

#[cfg(test)]
mod tests {
    #[test]
    fn adds_values() {
        assert_eq!(super::add(20, 22), 42);
    }
}
"""


class RustAdapterExecutionTests(unittest.TestCase):
    def setUp(self) -> None:
        families, _ = adapters.load_adapter_catalog()
        self.family = families["rust"]
        self.contracts: dict[str, dict[str, Any]] = {
            item["id"]: item for item in self.family["contracts"]
        }
        self.repositories: list[Repository] = []

    def tearDown(self) -> None:
        for repository in self.repositories:
            repository.close()

    def fixture(self) -> Repository:
        repository = Repository()
        self.repositories.append(repository)
        repository.write("rust-toolchain.toml", TOOLCHAIN)
        repository.write("Cargo.toml", MANIFEST)
        repository.write("Cargo.lock", LOCK)
        repository.write(".cargo/config.toml", "[net]\noffline = true\n")
        repository.write("src/lib.rs", SOURCE)
        repository.commit()
        return repository

    def native(self, root: Path, contract: dict[str, Any]) -> bool:
        wrapper = shutil.which("awq-rust-check")
        if wrapper is None:
            raise RuntimeError("pinned Rust wrapper is unavailable")
        prefix = Path(wrapper).resolve().parent.parent
        tool_bin = prefix / "rustup/toolchains" / "1.93.0-x86_64-unknown-linux-gnu" / "bin"
        cargo = tool_bin / "cargo"
        mode = contract["argv"][1]
        environment = {
            "PATH": f"{tool_bin}:/usr/bin:/bin",
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            "NO_COLOR": "1",
            "CARGO": str(cargo),
            "CARGO_HOME": str(prefix / "runtime-cargo"),
            "CARGO_NET_OFFLINE": "true",
            "CARGO_TERM_COLOR": "never",
            "RUSTC": str(tool_bin / "rustc"),
            "RUSTDOC": str(tool_bin / "rustdoc"),
        }
        if mode == "doc":
            environment["RUSTDOCFLAGS"] = "-D warnings"
        temporary_parent = os.environ.get("TMPDIR")
        with tempfile.TemporaryDirectory(
            prefix="awq-rust-native-",
            dir=temporary_parent,
        ) as scratch_name:
            scratch = Path(scratch_name)
            target = scratch / "target"
            temporary = scratch / "tmp"
            target.mkdir()
            temporary.mkdir()
            environment["CARGO_TARGET_DIR"] = str(target)
            environment["TMPDIR"] = str(temporary)
            completed = subprocess.run(
                [str(cargo), mode, *helper_arguments(mode)],
                cwd=root,
                env=environment,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=contract["timeout_seconds"],
                check=False,
            )
        return completed.returncode == 0

    def test_catalog_schema_order_mapping_and_runtime_boundary(self) -> None:
        validate(
            {"schema_version": 1, "families": [self.family]},
            "adapter-catalog.schema.json",
        )
        self.assertEqual(EXPECTED_IDS, list(self.contracts))
        for identifier in STABLE_IDS:
            contract = self.contracts[identifier]
            self.assertEqual("awq-rust-check", contract["tool"])
            self.assertEqual("1.0.0", contract["version"])
            self.assertEqual(CONFIG_PATHS, contract["config_paths"])
            self.assertEqual("explicit", contract["input_mode"])
            self.assertEqual([".rs", ".toml"], contract["formats"])
            arguments = " ".join(contract["argv"])
            self.assertNotIn("rustup", arguments)
            self.assertNotIn("install", arguments)
            self.assertFalse(any(argument.startswith("+") for argument in contract["argv"]))
            if contract["id"] != "ADAPTER-RUST-FMT":
                self.assertIn("--locked", helper_arguments(contract["argv"][1]))
                self.assertIn("--offline", helper_arguments(contract["argv"][1]))

    def test_every_contract_matches_native_success(self) -> None:
        repository = self.fixture()
        for identifier in STABLE_IDS:
            with self.subTest(identifier=identifier):
                contract = self.contracts[identifier]
                self.assertTrue(self.native(repository.root, contract))
                result = adapters.run_adapter(repository.root, contract)
                self.assertEqual("pass", result["status"])
                validate(result, "adapter-result.schema.json")

    def test_every_contract_matches_native_independent_failure(self) -> None:
        mutations = {
            "ADAPTER-RUST-BUILD": ('pub fn broken() -> u64 { "private-build-value" }\n'),
            "ADAPTER-RUST-CLIPPY": (
                "pub fn redundant(value: bool) -> bool {\n    if value { true } else { false }\n}\n"
            ),
            "ADAPTER-RUST-DOC": (
                "#![deny(rustdoc::broken_intra_doc_links)]\n"
                "/// Calls [private_missing_item].\n"
                "pub fn documented() {}\n"
            ),
            "ADAPTER-RUST-FMT": ("pub fn add(left:u64,right:u64)->u64{left+right}\n"),
            "ADAPTER-RUST-TEST": (
                "#[cfg(test)]\nmod tests {\n"
                "    #[test]\n"
                '    fn fails() { assert_eq!("private-left", "private-right"); }\n'
                "}\n"
            ),
        }
        for identifier, content in mutations.items():
            with self.subTest(identifier=identifier):
                repository = self.fixture()
                repository.write("src/lib.rs", content)
                repository.commit("negative")
                contract = self.contracts[identifier]
                self.assertFalse(self.native(repository.root, contract))
                result = adapters.run_adapter(repository.root, contract)
                self.assertEqual("fail", result["status"])
                self.assertEqual("adapter-failed", result["findings"][0]["code"])
                serialized = json.dumps(result)
                self.assertNotIn("private-", serialized)
                self.assertNotIn("private_", serialized)

    def test_lock_skew_and_missing_dependency_cache_fail_closed(self) -> None:
        repository = self.fixture()
        repository.write("Cargo.toml", MANIFEST.replace("0.1.0", "0.2.0"))
        repository.commit("lock skew")
        result = adapters.run_adapter(
            repository.root,
            self.contracts["ADAPTER-RUST-BUILD"],
        )
        self.assertEqual("fail", result["status"])
        self.assertEqual("adapter-failed", result["findings"][0]["code"])

        repository = self.fixture()
        repository.write(
            "Cargo.toml",
            MANIFEST + '\n[dependencies]\nitoa = "=1.0.18"\n',
        )
        repository.write(
            "Cargo.lock",
            LOCK.replace(
                'version = "0.1.0"\n',
                'version = "0.1.0"\ndependencies = ["itoa"]\n',
            )
            + '\n[[package]]\nname = "itoa"\nversion = "1.0.18"\n'
            'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
            'checksum = "8f42a60cbdf9a97f5d2305f08a87dc4e09308d1276d28c869c684d7777685682"\n',
        )
        repository.write(
            "src/lib.rs",
            "pub fn encoded(value: u64) -> String { itoa::Buffer::new().format(value).into() }\n",
        )
        repository.commit("uncached dependency")
        result = adapters.run_adapter(
            repository.root,
            self.contracts["ADAPTER-RUST-BUILD"],
        )
        self.assertEqual("fail", result["status"])
        self.assertEqual("adapter-failed", result["findings"][0]["code"])
        self.assertNotIn("itoa", json.dumps(result))

    def test_missing_tool_version_config_and_toolchain_skew_are_stable(self) -> None:
        contract = self.contracts["ADAPTER-RUST-BUILD"]
        repository = self.fixture()
        with mock.patch.object(shutil, "which", return_value=None):
            result = adapters.run_adapter(repository.root, contract)
        self.assertEqual("adapter-tool-unavailable", result["findings"][0]["code"])

        skewed = deepcopy(contract)
        skewed["version"] = "999"
        skewed["version_output"] = "awq-rust-check 999"
        result = adapters.run_adapter(repository.root, skewed)
        self.assertEqual("adapter-version-mismatch", result["findings"][0]["code"])

        for path in CONFIG_PATHS:
            with self.subTest(path=path):
                repository = self.fixture()
                target = repository.root / path
                target.unlink()
                result = adapters.run_adapter(repository.root, contract)
                self.assertEqual("adapter-config-missing", result["findings"][0]["code"])

        repository = self.fixture()
        repository.write(
            "rust-toolchain.toml",
            TOOLCHAIN.replace('channel = "1.93.0"', 'channel = "stable"'),
        )
        repository.commit("toolchain skew")
        result = adapters.run_adapter(repository.root, contract)
        self.assertEqual("fail", result["status"])
        self.assertEqual("adapter-failed", result["findings"][0]["code"])


def helper_arguments(mode: str) -> list[str]:
    arguments = {
        "build": ["--locked", "--offline", "--workspace", "--release"],
        "clippy": [
            "--locked",
            "--offline",
            "--workspace",
            "--all-targets",
            "--",
            "-D",
            "warnings",
        ],
        "doc": ["--locked", "--offline", "--workspace", "--no-deps"],
        "fmt": ["--all", "--", "--check"],
        "test": ["--locked", "--offline", "--workspace"],
    }
    return arguments[mode]


if __name__ == "__main__":
    unittest.main()
