# Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# SPDX-License-Identifier: MIT

"""Executable contracts for Rust supply-chain and API compatibility adapters."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import unittest
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from awq import adapters
from scripts import snapshot_rust_registry, snapshot_rust_semver
from scripts.validate_contracts import validate
from tests.support import Repository

SUPPLY_IDS = [
    "ADAPTER-RUST-ADVISORY",
    "ADAPTER-RUST-POLICY",
    "ADAPTER-RUST-SEMVER",
]
BINDING_KINDS = {
    "ADAPTER-RUST-ADVISORY": "advisory-db",
    "ADAPTER-RUST-POLICY": "registry-snapshot",
    "ADAPTER-RUST-SEMVER": "semver-baseline",
}
TOOLCHAIN = (
    '[toolchain]\nchannel = "1.93.0"\nprofile = "minimal"\ncomponents = ["clippy", "rustfmt"]\n'
)
MANIFEST = (
    '[package]\nname = "awq-supply-fixture"\nversion = "1.1.0"\n'
    'edition = "2024"\nlicense = "MIT"\npublish = false\n\n'
    '[lib]\npath = "src/lib.rs"\n'
)
LOCK = (
    "# This file is automatically @generated by Cargo.\n"
    "# It is not intended for manual editing.\n"
    "version = 4\n\n"
    "[[package]]\n"
    'name = "awq-supply-fixture"\n'
    'version = "1.1.0"\n'
)
SOURCE = """//! Public API fixture.

/// Stable public API.
#[must_use]
pub const fn awq_fixture_canary_api_7e91c2(value: u32) -> u32 {
    value
}
"""
DENY = """[bans]
multiple-versions = "deny"
wildcards = "deny"

[licenses]
confidence-threshold = 0.8
allow = ["MIT"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
  "https://github.com/rust-lang/crates.io-index",
]
"""


class RustSupplyAdapterExecutionTests(unittest.TestCase):
    def setUp(self) -> None:
        families, _ = adapters.load_adapter_catalog()
        family = families["rust"]
        self.contracts: dict[str, dict[str, Any]] = {
            item["id"]: item for item in family["contracts"] if item["id"] in SUPPLY_IDS
        }
        self.repositories: list[Repository] = []
        rust_wrapper = shutil.which("awq-rust-check")
        supply_wrapper = shutil.which("awq-rust-supply-check")
        if rust_wrapper is None or supply_wrapper is None:
            raise RuntimeError("pinned Rust and supply wrappers are unavailable")
        self.rust_prefix = Path(rust_wrapper).resolve().parent.parent
        self.supply_wrapper = Path(supply_wrapper).resolve()

    def tearDown(self) -> None:
        for repository in self.repositories:
            repository.close()

    def fixture(self) -> Repository:
        repository = Repository()
        self.repositories.append(repository)
        repository.write("rust-toolchain.toml", TOOLCHAIN)
        repository.write("Cargo.toml", MANIFEST)
        repository.write("Cargo.lock", LOCK)
        repository.write(".cargo/config.toml", "[net]\noffline = true\n")
        repository.write("deny.toml", DENY)
        repository.write("src/lib.rs", SOURCE)
        repository.json(
            "quality/rust-advisory-policy.json",
            {"ignored_advisories": [], "schema_version": 1},
        )
        snapshot_rust_registry.generate(
            repository.root,
            repository.root / "quality/rust-registry-snapshot.json",
            30,
        )
        snapshot_rust_semver.generate(
            repository.root,
            self.rust_prefix,
            "awq-supply-fixture",
            "awq_supply_fixture",
            "v1.0.0",
            "minor",
        )
        repository.commit()
        return repository

    def native(self, root: Path, mode: str) -> bool:
        environment = {
            "PATH": "/usr/bin:/bin",
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
        }
        temporary_parent = os.environ.get("TMPDIR")
        if temporary_parent is not None:
            environment["TMPDIR"] = temporary_parent
        completed = subprocess.run(
            [str(self.supply_wrapper), mode],
            cwd=root,
            env=environment,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=900,
            check=False,
        )
        return completed.returncode == 0

    def generate_lock(self, root: Path, *, allow_local_git: bool = False) -> None:
        toolchain = self.rust_prefix / "rustup/toolchains/1.93.0-x86_64-unknown-linux-gnu/bin"
        cargo = toolchain / "cargo"
        environment = {
            "PATH": "/usr/bin:/bin",
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            "CARGO_HOME": str(self.rust_prefix / "runtime-cargo"),
            "CARGO_NET_OFFLINE": "false" if allow_local_git else "true",
            "CARGO_TERM_COLOR": "never",
            "RUSTC": str(toolchain / "rustc"),
        }
        completed = subprocess.run(
            [str(cargo), "generate-lockfile"],
            cwd=root,
            env=environment,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=120,
            check=False,
        )
        self.assertEqual(0, completed.returncode)

    def assert_negative(
        self,
        repository: Repository,
        identifier: str,
        forbidden: tuple[str, ...],
    ) -> None:
        contract = self.contracts[identifier]
        mode = contract["argv"][1]
        self.assertFalse(self.native(repository.root, mode))
        result = adapters.run_adapter(repository.root, contract)
        self.assertEqual("fail", result["status"])
        self.assertEqual("adapter-failed", result["findings"][0]["code"])
        self.assertNotIn("bindings", result)
        serialized = json.dumps(result, ensure_ascii=False)
        for value in (str(repository.root), *forbidden):
            self.assertNotIn(value, serialized)
        validate(result, "adapter-result.schema.json")

    def test_catalog_contracts_are_explicit_and_schema_valid(self) -> None:
        self.assertEqual(SUPPLY_IDS, sorted(self.contracts))
        for identifier in SUPPLY_IDS:
            contract = self.contracts[identifier]
            self.assertEqual("awq-rust-supply-check", contract["tool"])
            self.assertEqual("1.0.0", contract["version"])
            self.assertEqual("awq-bindings-v1", contract["result_protocol"])
            self.assertEqual("explicit", contract["input_mode"])
            self.assertIn("Cargo.lock", contract["config_paths"])
            self.assertIn("rust-toolchain.toml", contract["config_paths"])
            validate(contract, "adapter-contract.schema.json")

    def test_every_contract_matches_native_success_and_emits_one_binding(self) -> None:
        repository = self.fixture()
        for identifier in SUPPLY_IDS:
            with self.subTest(identifier=identifier):
                contract = self.contracts[identifier]
                self.assertTrue(self.native(repository.root, contract["argv"][1]))
                result = adapters.run_adapter(repository.root, contract)
                self.assertEqual("pass", result["status"])
                self.assertEqual(1, len(result["bindings"]))
                self.assertEqual(BINDING_KINDS[identifier], result["bindings"][0]["kind"])
                validate(result, "adapter-result.schema.json")

    def test_license_lock_snapshot_advisory_and_api_failures_match_native(self) -> None:
        repository = self.fixture()
        repository.write(
            "Cargo.toml",
            MANIFEST.replace(
                'license = "MIT"',
                'license = "GPL-3.0-only"\ndescription = "fixture-secret-license"',
            ),
        )
        repository.commit("private license failure")
        self.assert_negative(
            repository,
            "ADAPTER-RUST-POLICY",
            ("fixture-secret-license", "GPL-3.0-only"),
        )

        repository = self.fixture()
        repository.write("Cargo.lock", LOCK + "\n# fixture-secret-lock\n")
        repository.commit("private lock skew")
        self.assert_negative(repository, "ADAPTER-RUST-POLICY", ("fixture-secret-lock",))

        repository = self.fixture()
        snapshot_path = repository.root / "quality/rust-registry-snapshot.json"
        snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))
        now = datetime.now(UTC).replace(microsecond=0)
        snapshot["generated_at"] = (now - timedelta(days=2)).isoformat().replace("+00:00", "Z")
        snapshot["expires_at"] = (now - timedelta(days=1)).isoformat().replace("+00:00", "Z")
        repository.json("quality/rust-registry-snapshot.json", snapshot)
        repository.commit("private stale registry")
        self.assert_negative(
            repository,
            "ADAPTER-RUST-POLICY",
            (str(snapshot["generated_at"]), str(snapshot["expires_at"])),
        )

        repository = self.fixture()
        repository.write(
            "Cargo.toml",
            MANIFEST + "# fixture-secret-advisory\n" + '\n[dependencies]\ntime = "=0.2.22"\n',
        )
        repository.write(
            "Cargo.lock",
            LOCK.replace(
                'version = "1.1.0"\n',
                'version = "1.1.0"\ndependencies = ["time"]\n',
            )
            + '\n[[package]]\nname = "time"\nversion = "0.2.22"\n'
            'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
            f'checksum = "{"0" * 64}"\n',
        )
        repository.commit("private advisory failure")
        self.assert_negative(
            repository,
            "ADAPTER-RUST-ADVISORY",
            ("fixture-secret-advisory",),
        )

        repository = self.fixture()
        repository.write(
            "src/lib.rs",
            "//! fixture-secret-api\n\npub const fn replacement(value: u32) -> u32 { value }\n",
        )
        repository.commit("private API break")
        self.assert_negative(
            repository,
            "ADAPTER-RUST-SEMVER",
            ("awq_fixture_canary_api_7e91c2", "fixture-secret-api"),
        )

    def test_duplicate_and_unapproved_git_source_failures_match_native(self) -> None:
        repository = self.fixture()
        repository.write(
            "Cargo.toml",
            MANIFEST + '\n[dependencies]\nduplicate_v1 = { package = "duplicate-fixture", '
            'version = "=1.0.0", path = "deps/v1" }\n'
            'duplicate_v2 = { package = "duplicate-fixture", '
            'version = "=2.0.0", path = "deps/v2" }\n',
        )
        for version in ("1.0.0", "2.0.0"):
            relative = "v1" if version.startswith("1") else "v2"
            repository.write(
                f"deps/{relative}/Cargo.toml",
                '[package]\nname = "duplicate-fixture"\n'
                f'version = "{version}"\nedition = "2024"\nlicense = "MIT"\n'
                '[lib]\npath = "src/lib.rs"\n',
            )
            repository.write(
                f"deps/{relative}/src/lib.rs",
                f'pub const VERSION: &str = "fixture-secret-duplicate-{version}";\n',
            )
        self.generate_lock(repository.root)
        snapshot_rust_registry.generate(
            repository.root,
            repository.root / "quality/rust-registry-snapshot.json",
            30,
        )
        repository.commit("private duplicate failure")
        self.assert_negative(
            repository,
            "ADAPTER-RUST-POLICY",
            ("fixture-secret-duplicate-1.0.0", "fixture-secret-duplicate-2.0.0"),
        )

        dependency = Repository()
        self.repositories.append(dependency)
        dependency.write(
            "Cargo.toml",
            '[package]\nname = "source-fixture"\nversion = "1.0.0"\n'
            'edition = "2024"\nlicense = "MIT"\n[lib]\npath = "src/lib.rs"\n',
        )
        dependency.write(
            "src/lib.rs",
            'pub const SOURCE: &str = "fixture-secret-git-source";\n',
        )
        dependency.commit()
        repository = self.fixture()
        repository.write(
            "Cargo.toml",
            MANIFEST + f'\n[dependencies]\nsource_fixture = {{ package = "source-fixture", '
            f'version = "=1.0.0", git = "file://{dependency.root}" }}\n',
        )
        self.generate_lock(repository.root, allow_local_git=True)
        snapshot_rust_registry.generate(
            repository.root,
            repository.root / "quality/rust-registry-snapshot.json",
            30,
        )
        repository.commit("private source failure")
        self.assert_negative(
            repository,
            "ADAPTER-RUST-POLICY",
            ("fixture-secret-git-source", str(dependency.root)),
        )

    def test_missing_project_policy_is_classified_before_execution(self) -> None:
        repository = self.fixture()
        for identifier, relative in (
            ("ADAPTER-RUST-ADVISORY", "quality/rust-advisory-policy.json"),
            ("ADAPTER-RUST-POLICY", "quality/rust-registry-snapshot.json"),
            ("ADAPTER-RUST-SEMVER", "quality/rust-semver-baseline.lock.json"),
        ):
            with self.subTest(identifier=identifier):
                path = repository.root / relative
                content = path.read_bytes()
                path.unlink()
                result = adapters.run_adapter(repository.root, self.contracts[identifier])
                self.assertEqual("adapter-config-missing", result["findings"][0]["code"])
                path.write_bytes(content)


if __name__ == "__main__":
    unittest.main()
